### ISSUE TITLE
cmake configuration without popt.pc

### ISSUE THREAD

**Issue by wwp** [shlomif/gringotts#2]
Since cmake now looks for popt.pc thru pkgconfig, it may fail on some systems where popt.pc is not installed whereas popt development packages *are* installed. For instance on Cent OS 7, popt-devel-1.13-16.el7.x86_64 does not bring popt.pc.
In that situation, it's easy to comment out the following lines in CMakeLists.txt:
```
pkg_check_modules (POPT REQUIRED popt)
IF (NOT POPT_FOUND)
	MESSAGE(FATAL_ERROR "You don't seem to have popt development libraries installed...")
ENDIF (NOT POPT_FOUND)
```
and run:
`$ cmake -D POPT_INCLUDE_DIRS=/usr/include -D POPT_LIBRARY_DIRS=/usr/lib64 -D POPT_LIBRARIES=libpopt.so`
In fact in Cent OS 7, it's not necessary to define POPT_INCLUDE_DIRS and POPT_LIBRARY_DIRS, cmake and the compiler will work using default include and library directories:
`$ cmake -D POPT_LIBRARIES=libpopt.so`

Is there a better way to do it?

**Comment by shlomif** [comment]
Hi @wwp ! Building gringotts works fine in fedora 32 x86-64 where `popt.pc` is provided. So I think this issue is invalid.

**Comment by wwp** [comment]
Well, what I mean is that the .pc file is not always there even if the popt version is compatible. In CentOS7, whereas the -devel package is installed, there is no .pc and it's possible to workaround this, using the tips I provided in my 1st post in this thread.

**Comment by wwp** [comment]
IOW, using the current CMakeLists.txt, cmake assumes popt.pc should be there: it's wrong (not always true), and it dumps the error "You don't seem to have popt development libraries installed": this is wrong (not always true).

**Comment by shlomif** [comment]
@wwp: I disagree.
