### ISSUE TITLE
`make install` does not rename $PREFIX/bin/gringotts-exe to $PREFIX/bin/gringotts

### ISSUE THREAD

**Issue by wwp** [shlomif/gringotts#3]
Here in CentOS 7, `make install` leaves $PREFIX/bin/gringotts-exe and I have to manually rename it to $PREFIX/bin/gringotts, where this code in CMakeLists.txt is supposed to do the job, isn't it?
`INSTALL (TARGETS "gringotts-exe" RUNTIME DESTINATION bin RENAME "gringotts")`

Tried with cmake3-3.17.2-1.el7.x86_64 and cmake3-3.17.2-1.el7.x86_64, same behaviour.

**Comment by shlomif** [comment]
Hi @wwp ! Thanks for the report. Try with current git master.  I was told on freenode #cmake that RENAME does not apply to TARGETS, so i used `install (PROGRAMS`.

**Comment by wwp** [comment]
It's better now. Thanks!

**Comment by shlomif** [comment]
Thanks @wwp ! Closing this issue then.
